version: 0.2

phases:
  install:
    #Ubuntu 표준 이미지 2.0 이상을 사용하는 경우 런타임 버전을 지정해야 합니다.
    #런타임 버전을 지정하는 경우 Ubuntu 표준 이미지 2.0 이외의 이미지를 사용하면 빌드에 실패합니다.
    runtime-versions:
      nodejs: 14
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      # npm config에 전역 캐시 폴더 설정
      - npm set cache .npm
      # ci 옵션을 통해 속도 개선
      - npm ci --prefer-offline --no-audit
  build:
    commands:
      - npm run start

  post_build:
    commands:
    
artifacts:
  files:
    - "**/*"
  base-directory: dist
cache:
  paths:
    - ".npm/**/*"